name: Ansible Lint
description: Run Ansible Lint
author: Ansible by Red Hat <info@ansible.com>
branding:
  icon: shield
  color: red
inputs:
  args:
    description: |
      Arguments to be passed to the ansible-lint.
    required: false
    default: "."
runs:
  using: docker
  image: docker://quay.io/ansible/creator-ee:v0.3.1
  entrypoint: /usr/local/bin/ansible-lint
  env:
    # These tell ansible-lint to use github compatible annotation format:
    GITHUB_ACTIONS: "true"
    GITHUB_WORKFLOW: "{{ github.workflow.name }}"
  args:
    - -vvv
    - ${{ inputs.args }}
